### ISSUE TITLE
Won't the PR's made in this repository be counted towards hacktoberfest 2021 ? As it shows a excluded project.

### ISSUE THREAD

**Issue by khan2810** [busybee23/Hacktoberfest-2021#127]
![Screenshot_2021-10-30-19-18-23-52_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://user-images.githubusercontent.com/56999345/139535650-96a94a4b-816e-4de8-8509-5997eccf2117.jpg)

**Comment by busybee23** [comment]
PR's related to DSA and programs will be excluded.

**Comment by busybee23** [comment]
Add your name in readme here : https://github.com/airbornesd/airbornesd.github.io
